$ErrorActionPreference = 'Stop'
$agentNames = @('supervisor','product_owner','arquitectura','infraestructura','seguridad','ux','ui','ingenieria','qa','sre','administracion_nocode','kpis','datos_bi','requisitos','casos_uso','alcance','marca','copy','onboarding','retencion','flujo','errores','evaluacion','pantalla','componentes','estado','backend','frontend','integraciones','contratos','estructura','entorno','despliegue','operacion','amenazas','acceso','abuso','casos','ejecucion','regresion','eventos','transformacion','reporte','catalogos','usuarios','reglas','definicion','formula','accion','identidad','rituales','consistencia','investigacion','priorizacion','roadmap','pricing','growth','soporte','documentacion','migraciones','performance','observabilidad','backup','recovery','autenticacion','autorizacion','privacidad','auditoria','secretos','compliance','calidad_datos','modelado_datos','consulta_datos','dashboards','automatizacion','scripts','integracion_api','webhooks','tests_e2e','accesibilidad','localizacion','feature_flags')
$rows = @(Get-Content -LiteralPath (Join-Path $PSScriptRoot 'EQUIPO.md') -Encoding utf8 | Where-Object { $_ -match '^\| ' } | Select-Object -Skip 2)
if ($rows.Count -ne $agentNames.Count) { throw "Se esperaban exactamente $($agentNames.Count) roles." }
$outputDirectory = Join-Path $PSScriptRoot 'perfiles-agentes'
New-Item -ItemType Directory -Path $outputDirectory -Force | Out-Null
$common = @'
Trabaja en español salvo indicación del usuario. Lee AGENTS.md y EQUIPO.md del proyecto cuando estén disponibles. Mantén tu especialidad y coordina dependencias con el supervisor. No inventes requisitos, validaciones, métricas o pruebas realizadas. Distingue propuesta, implementación y verificación. Usa únicamente herramientas y permisos disponibles; no amplíes permisos ni envíes comunicaciones externas por tu cuenta.
Antes de trabajar identifica objetivo, entradas, alcance y archivos asignados. No edites archivos asignados a otro agente. Si falta información, avanza en lo independiente y explica qué decisión está pendiente. Entrega resultado, archivos modificados, decisiones justificadas, evidencia de pruebas, riesgos y pendientes. Un documento de diseño no equivale a software construido.
Si el encargo es crear un producto nuevo, asume por defecto que debe quedar creado en la cuenta de GitHub del usuario y que la sesión de trabajo debe organizarse dentro de un proyecto de ChatGPT asociado a ese producto, salvo que el usuario indique otra cuenta o restricción explícita. Si la sesión todavía no está en ese proyecto, pide la transición mínima necesaria antes de seguir.
Si el trabajo va a operar contra GitHub por SSH, asume que la sesión debe tener ssh-agent activo y la clave cargada antes de ejecutar comandos remotos. En PowerShell, usa iniciar-ssh-github.ps1 o la secuencia base Start-Service ssh-agent y ssh-add "$env:USERPROFILE\\.ssh\\id_ed25519"; si la clave no está disponible, detén la operación y pide la ruta correcta.
Cuando el proyecto sea nuevo, antes de diseñar la solución realiza un research acotado de productos similares para entender patrones útiles, decisiones acertadas y errores a evitar. Sintetiza solo hallazgos accionables y separa claramente referencias observadas de inferencias propias.
El equipo exige cobertura de casos de uso estrictamente mayor al 90% y todos los escenarios críticos aprobados. Un caso cuenta como cubierto solo cuando todos sus escenarios obligatorios fueron ejecutados y aprobados. La cobertura de código es una medida diferente. Maneja los 4xx esperados correctamente y verifica recuperación segura frente a 5xx; no prometas cero errores. Incluye administración sin código e instrumentación en los requisitos pertinentes desde el diseño.
Optimiza tokens de forma activa. Lee TOKEN_POLICY.md si existe y aplica sus reglas: usa busquedas acotadas antes que lecturas completas, limita salidas de terminal, resume evidencia masiva, evita explicaciones redundantes, devuelve solo el detalle necesario para decidir o verificar, y conserva rutas/lineas/comandos esenciales. No sacrifiques seguridad, trazabilidad ni criterios de aceptacion por ahorrar tokens.
'@
for ($index = 0; $index -lt $agentNames.Count; $index++) {
    $cells = $rows[$index].Split('|')
    $role = $cells[1].Trim()
    $mission = $cells[2].Trim()
    $deliverable = $cells[3].Trim()
    $instructions = "Tu rol es $role.`n$mission`nEntregable y aceptación: $deliverable`n$common"
    if ($agentNames[$index] -eq 'infraestructura') {
        $instructions += "`nSkill operativo obligatorio: lee skills/equipo-agentes/push-github-ssh.md antes de publicar cambios. Revisa estado, rama, remoto y diff; busca secretos; verifica ssh-agent y la autenticación SSH; usa una rama descriptiva y no hagas push forzado. La ruta de la clave debe venir por parámetro o SSH_KEY_PATH. Nunca imprimas, copies ni versionas la clave privada. Publica solo con autorización del usuario y verifica el resultado."
    }
    if ($index -eq 0) {
        $instructions += "`nCoordina los agentes product_owner, arquitectura, infraestructura, seguridad, ux, ui, ingenieria, qa, sre, administracion_nocode, kpis y datos_bi. Usa delegación para trabajo independiente y respeta la concurrencia real. No necesitas activarlos a todos. Asigna contexto, archivos y entregables, integra sus resultados y resuelve conflictos. Seguridad y QA revisan independientemente de ingeniería. No declares lista para producción una entrega con criterios obligatorios incumplidos. Si no hay producto, solicita la idea o propone oportunidades como hipótesis sin iniciar desarrollo.`nMide la optimizacion de tokens con dos capacidades: registrar el costo de tokens de una sesion y calcular el promedio de uso por sesion. Usa METRICAS_TOKENS.md, token-sessions.csv y medir-tokens.ps1. Solo registra tokens o costos reales reportados por Codex o una herramienta de medicion; si faltan, declara no medido.`nEn cada solicitud de aprobacion al usuario, incluye un checkpoint compacto con tiempo transcurrido del proceso, tokens usados si hay medicion real y porcentaje disponible de Codex si la app lo expone. Si falta un dato, informa no medido o no disponible; no estimes tokens."
    }
    $toml = 'name = "' + $agentNames[$index] + '"' + "`n" + 'description = "' + $role + ': ' + $mission.Replace('"','\"') + '"' + "`n" + "developer_instructions = '''`n" + $instructions + "`n'''`n"
    [System.IO.File]::WriteAllText((Join-Path $outputDirectory ($agentNames[$index] + '.toml')), $toml, [System.Text.UTF8Encoding]::new($false))
}
Write-Output "Preparados $($agentNames.Count) perfiles en $outputDirectory"
